travis:
  secure:
    BINSTAR_TOKEN: bNmGsEB9gfmbcsvlfGfHzKloMn2+Fhzqqe5f8awkQsNoCD4LpWjs88k1FSDP9o9gtEWhUQcmj26RyMPiHmnYhogVLqEcsoIOLYEfhCPf+pKbweJS7yCmA/OpluBX6l7SGcbykCozIcCLk+Q/STI/VctCcNWrJ8waug/4hc+gzNEV6S8d/7ccf7t7FRa3HNDDbk5lM8EWwCJKqCsZJc5i1EXaw/giLomEGfiMD1+hsySgLbZyiWNWDIrxvfItWdIB9zQf9GXXeUvE1YjQsHLiqFUeiXmQvj+X8y7xkpK4eZk8Mx23JG9FVbs/CNwkr3+IOxclkIWyPWpVzk2HnlraVjycEDgPOO6HO7Vlg0e8TUDNFBLIUyMxx+uT43jOTduHWwhK25geivberNap+v+DJw4lIlQHnN+5sJb9ghmhcfQRVcm2Ai0GA8ouHG18jZUDiwXoeu6wKL72zhBGCScQZJ4ikZPkOOkipLJ3xDlp3FCwim6TDMVjBr5jDV3iFVMF+k1anF4aFCDqqoSGXTsdaegMtoE4I1E5Ccgfx+Q8fDZVScPxjPGN8si8KHIgg6+1k4Lxq5uK+8G8UzJrdR9s2Xw2BtSLt3fisskVx4QXd7j00TyZ3z8xVZQ23vBz48dP5rH6AS//elQ8e881OOL+70w+850PkxZq5Hdxz/Ydr+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
